branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: chemicals-near-me-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
