version: "3"
services:
  frontend:
    image: lorenzomtzz/frontend
    build: ./frontend
    ports:
      - 3000:3000
    command: npm start
    
  backend:
    image: lorenzomtzz/backend
    build: ./backend
    ports:
      - 80:80
    command: ./start.sh